apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: cy7e2ifae-java-springboot
  janus-idp.io/tekton: cy7e2ifae-java-springboot
  backstage.io/kubernetes-id: cy7e2ifae-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: cy7e2ifae-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
